### ISSUE TITLE
Форма заказа у заказчика. (Добивает Костя)

### ISSUE THREAD

**Issue by monty28** [calmarcher/dipstart-development#13]
У заказчика сей час получилось 2 формы заказа.  Одна чат, вторая в ссылке по номеру заказа. 
Обе правильные на 50%, нам нужно сделать одну толковую.  
За основу берем ту, что по ссылке “Чат” > http://dipstart.coolfire.pp.ua/index.php?r=project/chat&orderId=6  
Блок с инфой о заказе делаем как во второй (этой) форме > http://dipstart.coolfire.pp.ua/index.php?r=project/zakaz/update&id=6 
Т.е делаем редактируемые поля. (Блок стоимости не нужен.)

**Comment by nicdnepr** [comment]
почитал задание. не понятно зачем объединять эти две формы если они разные по смыслу. 

http://dipstart.coolfire.pp.ua/index.php?r=project/chat&orderId=6 форма чата нужна только для чата,зачем там еще выводить поля заказа? 

http://dipstart.coolfire.pp.ua/index.php?r=project/zakaz/update&id=6 а тут форма для редактирования заказа

**Comment by monty28** [comment]
У заказчика будет только одна форма заказа в личном кабинете. Включающая в себя сразу Информацию о заказе и чат, как и у менеджера.

**Comment by nicdnepr** [comment]
тогда я предлагаю добавить новый чат на эту форму http://dipstart.coolfire.pp.ua/index.php?r=project/zakaz/update&id=6

**Comment by nicdnepr** [comment]
1 час
