### ISSUE TITLE
Статусы заказа. 

### ISSUE THREAD

**Issue by monty28** [calmarcher/dipstart-development#14]
1. Новый заказ.
 - При оформлении заказ сразу получает данный статус
2. Ждем решения клиента (или предоплаты) - название ещё скорректируем.
 - Заказ приобретает данный статус, когда менеджер выставил сумму к оплате заказчику.
3. Поиск Автора
 - Данный статус назначается, когда заказчик загрузил файл в окошко чеки (которое сделаем).  
 - Так-же данный статус назначается, когда в чате сняли исполнителя. 
4. Автор работает (приступил\назначен). Называть как угодно.
 - Заказ приобретает такой статус, когда в чате назначили исполнителя. 
5. Завершен
 - Заказ получает такой статус, когда менеджер сохранил заказ оставив поле “Дата информирования (менеджер)” пустым.

**Comment by monty28** [comment]
При Новый заказ. - Заказ у Авторов не отображается.
Ждем решения клиента - Заказ так-же у Автора не отображается. 
Поиск Автора - Заказ видят Авторы в разделе "Новые заказы"
Автор работает - Авторы не видят заказ в новых. Заказ остается лишь в разделе "Мои заказы" у того Автора, что назначен исполнителем.

**Comment by monty28** [comment]
Нужно в раздел личный счет заказчику. Добавить возможность загружать файл. Это будет чек оплаты.   У менеджера в кабинете, это окошко будет отображаться где-то в блоке оплаты. 
И как только заказчик загружает в это окошко файл. Статус меняется: 
с "Ждем решение клиента"  на  "Поиск Автора"

**Comment by nicdnepr** [comment]
2 часа
