### ISSUE TITLE
События

### ISSUE THREAD

**Issue by monty28** [calmarcher/dipstart-development#16]
- События после перехода в них менеджера, должны исчезать. Нужно реализовать функцию...

**Comment by Emericanec** [comment]
2 часа

**Comment by Emericanec** [comment]
При создании задачи она не попадала на модерацию а сразу попадала в задачи. Сделал что все задачи попадают на модерацию если его создал не Админ.

**Comment by monty28** [comment]
Пока что, события не работают должным образом.

**Comment by nicdnepr** [comment]
1 час

**Comment by monty28** [comment]
Изменения в профиле пользователей не исчезают, сделать, как и остальные события. 
Событие: "Пользователь изменил данные в профиле"

**Comment by nicdnepr** [comment]
должно работать
