### ISSUE TITLE
Блок Сроки

### ISSUE THREAD

**Issue by monty28** [calmarcher/dipstart-development#18]
Изменить названия полей.  На : 
1. Дата оформления.
2. Срок сдачи
3. Дата защиты
6. Срок для Автора
Строку 4 - Удалить
*Строку 5 - Оставить без изменений
Номера строк указаны в порядке их расположения в админке.

**Comment by monty28** [comment]
Пункт 2: 
Должна быть возможность сохранить поля в пустом состоянии. 
И стандартно в них должна быть не дата 1970 год. (Как сейчас), а пустое поле.

**Comment by nicdnepr** [comment]
2 часа
