### ISSUE TITLE
Чат 

### ISSUE THREAD

**Issue by monty28** [calmarcher/dipstart-development#2]
Была задача перенести чат. Чат несколько изменился - это ладно. Но всё в чате должно работать, ведь оно работало. Кнопки ответить и переадресовать.и пр..

**Comment by monty28** [comment]
Сделать кнопки:
- Отправить автору - Отправляет сообщение текущему автору.
- Отправить заказчику - Отправляет сообщение заказчику.
- Кнопка “Ответить” на сообщение от Заказчика или Автора - выбирает адресата конкретного пользователя.  После чего менеджер вводит текст сообщения.

**Comment by coolfire79** [comment]
Вот так. Моё!

**Comment by monty28** [comment]
- Не отображается цена за работу. (У Автора при отправке сообщения сделано отдельное поле для ввода цены).
- Логин автора должен быть ссылкой на его профиль
- После одобрения сообщения в чате, галочка “одобрить” должна пропадать. А то не понятно одобрено или нет.

**Comment by monty28** [comment]
- Не доходят сообщения от Менеджера к Заказчику.

**Comment by monty28** [comment]
- Не доходят сообщения от Менеджера к Заказчику и Автору.

**Comment by monty28** [comment]
При нажатии ответить. Должен быть выбран получатель. Выводить текст : Вы писали: <<*******>> 
не нужно.

**Comment by monty28** [comment]
- заказчик и автор не видят своих сообщений у себя в чате. 
 - сообщения от манагера, доходят как Заказчику, так и Автору.
