### ISSUE TITLE
Блок оплаты + бухгалтерия

### ISSUE THREAD

**Issue by monty28** [calmarcher/dipstart-development#23]
При оплате автору, устанавливается сумма к оплате Автору, которая идет в бухгалтерию.
Бухгалтер? после того как перевел оплату Автору, подтверждает, что платеж осуществлен. 
И сумма, в блоке оплаты (в форме заказа). Из поля "Суммарно на оплату:" переносится в поле "Оплачено работы:"
В данный момент, после того, как в бухгалтерии нажата кнопка подтвердить.  В форме заказа ничего не изменяется.

**Comment by nicdnepr** [comment]
уточнения- вводим сумму в поле Отправить на оплату, число попадает в раздел Суммарно на оплату. после подтверждения в разделе бухгалтерия сумма Суммарно на оплату должна перейти в раздел Оплачено работы
все верно?

**Comment by monty28** [comment]
да

**Comment by nicdnepr** [comment]
2 часа
