### ISSUE TITLE
Генерация сроков.

### ISSUE THREAD

**Issue by monty28** [calmarcher/dipstart-development#27]
Поле. "Дата информирования (менеджер)" при оформлении заказа должна генерироваться на "сегодняшнее" число. Ну можно сказать, должно генериться таое-же значение как в поле дата оформления.  
Поле "Срок для Автора" должно генерироваться в 2 раза меньше, чем общий срок для сдачи. 
Т.е должно высчитывать разницу полей  % "Срок для сдачи" - "дата офрмления" \ 2 %

**Comment by nicdnepr** [comment]
это заданиме +№26 1 час
