### ISSUE TITLE
Сроки указанные заказчиком при регистрации - не сохранились. 

### ISSUE THREAD

**Issue by monty28** [calmarcher/dipstart-development#6]

**Comment by nicdnepr** [comment]
не понятно какие сроки при регистрации

**Comment by monty28** [comment]
При регистрации заказа, у заказчика всего 2 срока. Он ставит срок в который нужно сделать работу "Максимальный срок" и "Дата Завершения".  http://shot.qip.ru/00f8q2-6Myy9DMLj/

**Comment by nicdnepr** [comment]
1 час
