### ISSUE TITLE
Страница регистрации заказчика

### ISSUE THREAD

**Issue by monty28** [calmarcher/dipstart-development#7]
При регистрации заказчика, нет необходимости в ограничении поля “город” по кол-ву символов. Мало-ли город “Орел” будет, к примеру. 
http://shot.qip.ru/00f8q2-5Myy9DMIl/

**Comment by nicdnepr** [comment]
насколько я понял счас город вобще не сохраняется

**Comment by monty28** [comment]
Да, верно замечено, там как-то не верно настроено, значение стоит непонятное.

**Comment by nicdnepr** [comment]
1 час

**Comment by nicdnepr** [comment]
для внесения изменений нужно на рабочем сервере в каталоге с проектом выполнить команду protected/yiic migrate
