### ISSUE TITLE
Форма заказа (менеджер) - Поля. 

### ISSUE THREAD

**Issue by monty28** [calmarcher/dipstart-development#9]
Добавить все недостающие поля смотрим: *https://docs.google.com/document/d/1jyhmHfJSF5k1O0jdqVSclzToENKEmLj6hK2JH1plCDk/edit#bookmark=id.4bx3cuwnc2jt 
Не хватает файлов к заказу и полей: “удобное время для связи” и “учебное заведение”

**Comment by nicdnepr** [comment]
тут нужно уточнение по полям

**Comment by monty28** [comment]
Поля “удобное время для связи” и “учебное заведение” - самые обычные поля с текстом (редактируемые), которые заполняет заказчик при оформлении.  
В целом сравнимы с др. полями, такими как например : "Доп. требования"

**Comment by nicdnepr** [comment]
>>Не хватает файлов к заказу
что насчет этого?

**Comment by monty28** [comment]
Обычное поле, в котором прикрепляются файлы.

**Comment by nicdnepr** [comment]
я счас смотрю форму редактирования заказа -там уже есть раздел доработки и части для добавления файлов

**Comment by monty28** [comment]
Это добавление файлов в блок доработки. А нужно добавление файлов в форме заказа ещё непосредственно.  Прикладывать материалы к заказу.

**Comment by monty28** [comment]
Дима, в форме регистрации заказа тоже нужны эти поля.
